name: Deploy do To-Do App para o Docker Hub

amlon:
  push:
    branches:
      - master

jobs:
  build-e-push:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ERIKLINS }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Passo 3: Build e Push da imagem
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: eriklins/todo-app:latest

  